apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkit-deployment
  namespace: parkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkit
  template:
    metadata:
      labels:
        app: parkit
    spec:
      containers:
        - name: parkit-container
          image: localhost:5000/oceanmoist/parkit:1.0.144
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: dbuser
            - name: DB_PASSWORD
              value: dbpassword
            - name: DB_NAME
              value: db
            - name: GITHUB_CLIENT_ID
              value: im not that dumb
            - name: GITHUB_CLIENT_SECRET
              value: get your own
          imagePullPolicy:
            Always
